cloudinary:
    api-key: 481153665422683
    api-secret:
    cloud-name: dtns2qohp
logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
mail:
    host: smtp.gmail.com
    mailsender: remontprojectbgsoftuni@gmail.com

    password:
    port: 587
    username: remontprojectbgsoftuni@gmail.com

server:
    port: 8000
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/remont_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
